apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: gitlab-authorization
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "attach", "delete", "exec", "get"]
- apiGroups: [""]
  resources: ["pods/logs"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "update"]
- apiGroups: [""]
  resources: ["serviceAccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test
  name: gitlab-authorization-rolebinding
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: test
roleRef:
  kind: Role
  name: gitlab-authorization
  apiGroup: rbac.authorization.k8s.io
